import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const profileScreenStyles = StyleSheet.create({
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  avatarInitials: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
  },
  avatarWrap: {
    position: 'relative',
  },
  bloodTypePill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderRadius: radii.pill,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bloodTypePillText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    gap: 16,
    padding: 16,
    ...shadows.card,
  },
  cardTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '800',
  },
  contactIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  contactLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  contactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  contactValue: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '600',
  },
  contactValueWrap: {
    flex: 1,
    gap: 2,
  },
  divider: {
    backgroundColor: colors.border,
    height: 1,
    width: '100%',
  },
  donationDate: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
  },
  donationHospital: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  donationIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  donationItem: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  donationTextWrap: {
    flex: 1,
    gap: 2,
  },
  editProfileButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 12,
  },
  editProfileText: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  emptyDonationsText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  header: {
    backgroundColor: colors.card,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingBottom: 16,
    paddingHorizontal: 24,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerSettingsButton: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  headerTitle: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  linkText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 16,
    ...shadows.card,
  },
  logoutText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  menuBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    minWidth: 22,
    paddingHorizontal: 6,
  },
  menuBadgeText: {
    color: colors.primaryForeground,
    fontSize: 11,
    fontWeight: '800',
  },
  menuIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  menuLabel: {
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
  },
  menuRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  menuRowDivider: {
    backgroundColor: colors.border,
    height: 1,
  },
  overviewCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.cardLg,
    borderWidth: 1,
    gap: 16,
    padding: 20,
    ...shadows.card,
  },
  overviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 16,
  },
  nameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  overviewMeta: {
    flex: 1,
    gap: 6,
  },
  roleLabel: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '500',
  },
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContent: {
    gap: 16,
    paddingBottom: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statColumn: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  statRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statValue: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  userName: {
    color: colors.foreground,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '800',
  },
  verifiedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.successSoft,
    borderRadius: radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  verifiedBadgeOnAvatar: {
    alignItems: 'center',
    backgroundColor: colors.success,
    borderColor: colors.card,
    borderRadius: 999,
    borderWidth: 2,
    bottom: 0,
    height: 22,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 22,
  },
  verifiedBadgeText: {
    color: colors.success,
    fontSize: 12,
    fontWeight: '700',
  },
});
