import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const nearbyDonorsMapStyles = StyleSheet.create({
  chip: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 14,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipLabel: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '600',
  },
  chipLabelActive: {
    color: colors.primaryForeground,
    fontWeight: '700',
  },
  chipRow: {
    gap: 8,
    paddingRight: 24,
  },
  chipScroll: {
    flexGrow: 0,
  },
  donorList: {
    gap: 12,
    paddingBottom: 28,
  },
  donorSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  donorSectionTitle: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    gap: 12,
    padding: 20,
    ...shadows.card,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  errorText: {
    color: colors.primary,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  filterLink: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  header: {
    backgroundColor: colors.card,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    gap: 12,
    paddingBottom: 12,
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  headerSubtitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  headerTitle: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  headerTitleBlock: {
    gap: 2,
  },
  listContent: {
    gap: 16,
    paddingBottom: 8,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  listScroll: {
    flex: 1,
  },
  mapControls: {
    gap: 8,
    left: 12,
    position: 'absolute',
    top: 12,
    zIndex: 4,
  },
  mapControlButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
    ...shadows.card,
  },
  mapControlButtonPressed: {
    opacity: 0.9,
  },
  mapLoadingBadge: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'absolute',
    right: 12,
    top: 56,
    zIndex: 4,
    ...shadows.card,
  },
  mapLoadingText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  mapSection: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  mapSummaryCard: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    bottom: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    right: 12,
    zIndex: 4,
    ...shadows.card,
  },
  mapSummaryLabel: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
  mapSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mapSummaryStat: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '700',
  },
  mapSummaryStatMuted: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '600',
  },
  mapWrapper: {
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  permissionBanner: {
    backgroundColor: colors.primaryTint,
    borderColor: colors.borderAccent,
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    marginHorizontal: 24,
    marginTop: 12,
    padding: 12,
  },
  permissionText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  searchInput: {
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  searchShell: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 46,
    paddingHorizontal: 14,
  },
  visibilityCard: {
    backgroundColor: colors.card,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    gap: 4,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  visibilityCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  visibilityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  visibilityTitle: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
});
